### PR TITLE
Get fluid properties for multiple temperatures

### PR DESCRIPTION
**Pull request by wouterpeere**
Dear @mitchute 

I wanted to use SecondaryCoolantProps to get fluid properties for multiple temperature values, but this was not possible.
Therefore I added the possibility for the temp variable to be either a float of an iterable input.

What do you think?

Best,
@wouterpeere

### CODE REVIEW

**Comment by mitchute** [comment]
@wouterpeere Thanks! I'm not opposed to making this happen, though, we had originally built this out to be an ultra-minimal library. Adding Numpy as a dependency is my only real complaint. Numpy is pretty much a part of everything anyway, so maybe that isn't a hill worth dying on.

@Myoldmopar any thoughts?

**Comment by Myoldmopar** [comment]
My gut instinct says that it would be easy enough to just call the temperature value functions multiple times and avoid having a dependency on Numpy.  I agree the changes are minimal enough, but as you mentioned, it was meant to be extremely lightweight and avoid dependencies.  

What if someone created a SecondaryCoolantPropsNumPy Python package, with two dependencies -- this library and numpy.  And then just expose a few new functions that wrap over this library and expose a numpy-enhanced API.  Could be a fun little 45 minute adventure :)

All that said, my personal vote would be a no, but I'm not going to stand in the way if it really is worth making the change inside this library.

**Comment by wouterpeere** [comment]
@mitchute and @Myoldmopar 

Thanks for the response!
I know that this repo was built as an extremely lightweight solution and I thought of calling the temperature value function multiple times. However, function calling adds a lot of overtime in python, therefore this was not my ideal solution.

The same behavior can also be implemented in a purely Pythonic way, using lists and iterators, but this is also rather slow.

I would also be open for the option of creating a child repo where there is a numpy dependency, but perhaps this is not ideal for further development and intercompatibility?

**Comment by Myoldmopar** [comment]
OK, so if we are going to talk about performance, we need to have numbers to back it up.  I ran some tests on our base branch as well as the new branch that modifies the calls to use numpy.  I wanted to see the impact of the change in 3 scenarios:
 - Our base branch, calling the functions with a single temperature value and returning a single value
 - The new branch, but without modifying the client code -- this is essentially testing what will happen to any existing codebases that rely on our current API
 - The new branch, but with the client using a list of temperatures as an argument -- this is the desired way forward with the new branch.

For each scenario, I wanted to know what would happen when the functions were called with a variety of temperature counts, so I tested a few different # of temperatures - from 1 up to 100,000 with a few steps along the way.

For each test, I ran 5 tests and averaged the results.  I then scaled the runtime into a "per-function-call" runtime, in ms.  The result is essentially a representative amount of time it takes to calculate a single property.  You would expect that with the new branch, the average runtime would improve as you calculated more and more properties, because we are eliminating that overhead of many function calls.  

Here is the test code I was running, so that you can replicate things:

```
import time

from scp.propylene_glycol import PropyleneGlycol

p = PropyleneGlycol(0.0)
num_temps_to_check = [1, 3, 8, 15, 40, 100, 1000, 10000, 100000]
num_tests = 5
print("NumTemperaturesCalculated,AverageTotalRuntime,AverageTimePerFunctionCall")
for temp_count in num_temps_to_check:
    temps_list = [x / temp_count for x in range(temp_count)]
    summation_ms = 0
    for n in range(num_tests):
        start_tick = time.perf_counter()
        
        # use this for the old calling method
        # [p.specific_heat(t) for t in temps_list]
        
        # use this for the new numpy enabled API
        p.specific_heat(temps_list)
        
        end_tick = time.perf_counter()
        summation_ms += 1000 * (end_tick - start_tick)
    
    avg_total_time = summation_ms / num_tests
    print(f"{temp_count},{avg_total_time},{avg_total_time / temp_count}")
```

Here is the resulting chart:
image

There are some interesting things to note:
- First of all a baseline, the red column represents the current branch.  As expected, the amount of time spent evaluating a single function call does not change much with the amount of function calls made.  Each time, we simply call the function N times, and it takes roughly the same amount of time to make the function call to evaluate a single property.
- OK, so now let's see what happens when we use the new branch, but we still call it the same way.  In this case, we are going to be constructing numpy intermediates, just to calculate a single value.  This is proving to be a much more expensive process than just operating on scalars directly.  The extra time spent constructing numpy pieces just to calculate a scalar value looks to be problematic, and as expected, does not get much better as the number of function calls increases.  This is an important outcome for our project, as a simple update to a new version would unexpectedly encounter possibly major runtime increases unless the client reworks their code.
- Finally, the new branch in the new method.  When calling with a list of 1 value, there is a lot of extra overhead, and this is very slow.  I wouldn't expect this to be a meaningful test, because most people would be calling the list version with more than one value.  Once we move into multiple values, the new code is running much faster, and as you do more and more, it just gets faster on a per-function-call basis.  This is a great, and expected, result.

I am worried about the impact of arbitrarily increasing the runtime of existing projects that call with a scalar, just because they updated to a newer version of our package.  Is there any way that we could modify our API and _add_ new endpoints that are list-based, but leave the scalar versions alone? 

And for kicks, here is the resulting tabular data:
| Base Branch – Calling one temperature at a time (current way)                                  |                     |                            |
|------------------------------------------------------------------------------------------------|---------------------|----------------------------|
| NumTemperaturesCalculated                                                                      | AverageTotalRuntime | AverageTimePerFunctionCall |
| 1                                                                                              | 0.00232751481235027 | 0.00232751481235027        |
| 3                                                                                              | 0.00378256663680077 | 0.00126085554560026        |
| 8                                                                                              | 0.00869734212756157 | 0.0010871677659452         |
| 15                                                                                             | 0.015554204583168   | 0.0010369469722112         |
| 40                                                                                             | 0.0410611275583506  | 0.00102652818895876        |
| 100                                                                                            | 0.107048917561769   | 0.00107048917561769        |
| 1000                                                                                           | 1.05281481519341    | 0.00105281481519341        |
| 10000                                                                                          | 10.4724747594446    | 0.00104724747594446        |
| 100000                                                                                         | 103.916159132496    | 0.00103916159132496        |
|                                                                                                |                     |                            |
| New Branch – Calling one temperature at a time (how current code would work in the new branch) |                     |                            |
| NumTemperaturesCalculated                                                                      | AverageTotalRuntime | AverageTimePerFunctionCall |
| 1                                                                                              | 0.0360946170985699  | 0.0360946170985699         |
| 3                                                                                              | 0.0817354302853346  | 0.0272451434284449         |
| 8                                                                                              | 0.213966937735677   | 0.0267458672169596         |
| 15                                                                                             | 0.401630997657776   | 0.0267753998438517         |
| 40                                                                                             | 1.07009564526379    | 0.0267523911315948         |
| 100                                                                                            | 2.66740252263844    | 0.0266740252263844         |
| 1000                                                                                           | 16.8734392616898    | 0.0168734392616898         |
| 10000                                                                                          | 144.411829765886    | 0.0144411829765886         |
| 100000                                                                                         | 1444.41107134335    | 0.0144441107134335         |
|                                                                                                |                     |                            |
| New Branch – Calling once with a list of temperatures (desired new way)                        |                     |                            |
| NumTemperaturesCalculated                                                                      | AverageTotalRuntime | AverageTimePerFunctionCall |
| 1                                                                                              | 0.0543100759387016  | 0.0543100759387016         |
| 3                                                                                              | 0.0311206560581923  | 0.0103735520193974         |
| 8                                                                                              | 0.0317211262881756  | 0.00396514078602195        |
| 15                                                                                             | 0.0327790156006813  | 0.00218526770671209        |
| 40                                                                                             | 0.0331239309161902  | 0.000828098272904754       |
| 100                                                                                            | 0.0353096053004265  | 0.000353096053004265       |
| 1000                                                                                           | 0.0735484063625336  | 7.35E-05                   |
| 10000                                                                                          | 0.529161561280489   | 5.29E-05                   |
| 100000                                                                                         | 5.89819741435349    | 5.90E-05                   |

**Comment by wouterpeere** [comment]
Hi @Myoldmopar 

What an interesting result! I was not aware that the conversion of a scalar to numpy added such an overload in the code.
I changed the code in such a way that it handles scalars the same way as before and only converts lists to numpy. This gets the runtime back to the same order of magnitude as your first experiment, however still somewhat slower, due to the extra checks I think.

**Comment by wouterpeere** [comment]
Hi @mitchute 

Did you have the chance to take a closer look at this PR and the new commits?

**Comment by mitchute** [comment]
@wouterpeere thanks for the reminder. I pulled up both branches and ran the above code snippet again and am seeing similar results to what @Myoldmopar reported.

image

At this point, I don't see a good argument for accepting it as is. We're adding a new dependency, which isn't a big issue, but should be noted. Next, current users who don't adopt the new approach will see roughly a 3X slowdown per call, so that's not good. Finally, if they do adopt the new list-based approach and don't understand that the break-even point between the single-temp-per-call and list-based approach is somewhere between 3 and 8, then they potentially could see much, much larger slowdowns.

I think this needs a separate calling path if you want to expose the list-based approach here. I didn't see a good way to do that without a little code duplication. If you want to explore that, feel free. Or if you'd rather just point to your fork, I'm OK with that, too.

**Comment by wouterpeere** [comment]
Hi @mitchute 

I made some final changes to get everything even faster, but in the end, I have to agree. These are my final results:
image

The runtime is now the same for scalars, but the advantage of using a list input instead of iterating over the current function, comes after 8 function calls. I agree this is not worth it.

It was an interesting exercise; I was not aware that numpy added that much of overhead.

**Comment by Myoldmopar** [comment]
@wouterpeere I appreciate you going through this exercise with us, it was very helpful for me as well!

**Pull request closed without merging**
